baseURL = "https://example.com"
languageCode = "en-us"
title = "Logis"
theme = "logis"

# Menu items
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Services"
    url = "/services"
    weight = 3
  [[menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5

  [[menu.dropdown]]
    name = "Dropdown 1"
    url = "/dropdown1"
    weight = 1
  [[menu.dropdown]]
    name = "Dropdown 2"
    url = "/dropdown2"
    weight = 2
  [[menu.dropdown]]
    name = "Dropdown 3"
    url = "/dropdown3"
    weight = 3

# Site parameters
[params]
  # Footer text
  footer.description = "Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus."
  footer.credits = "Designed by <a href='https://yourwebsite.com/'>Your Name</a>"
  
  # Contact information
  [params.contact]
    email = "info@example.com"
    phone = "+1 5589 55488 55"
  
  # Address
  [params.address]
    street = "A108 Adam Street"
    city = "New York"
    state = "NY"
    zip = "535022"
    country = "United States"
  
  # Social media links
  [[params.social]]
    icon = "twitter"
    url = "#"
  [[params.social]]
    icon = "facebook"
    url = "#"
  [[params.social]]
    icon = "instagram"
    url = "#"
  [[params.social]]
    icon = "linkedin"
    url = "#"