name = "Logis"
license = "MIT"
licenselink = "https://github.com/yourusername/logis/blob/master/LICENSE"
description = "A modern Hugo theme for logistics and delivery companies"
homepage = "https://github.com/yourusername/logis"
tags = ["logistics", "business", "responsive", "modern", "corporate"]
features = ["responsive", "bootstrap", "company"]
min_version = "0.41.0"

[author]
  name = "Anbumani Mailathipathy"
  homepage = "https://creativestudio14.com"